services:
  back-end:
    build: ./Back-end
    ports:
      - 8080:8080
    environment:
      - USERNAME=${USERNAME}
      - PASS=${PASS}
      - ROOT=${CONTAINER_ROOT_PATH}
    volumes:
      - ${HOST_ROOT_PATH}:${CONTAINER_ROOT_PATH}

  front-end:
    build: ./Front-end
    ports:
      - 5173:5173
    depends_on:
      - back-end